### ISSUE TITLE
Fix `leaves` type in Merklize

### ISSUE THREAD

**Issue by aashutoshrathi** [stackrlabs/succinct-residency-exps#29]
## Description
Right now the leaves are of type `Vec<Vec<u8>>`, it can be `Vec<[u8; n]>`

**Comment by 0xRampey** [comment]
The leaves we pass in can have arbitrary sizes, they are hashed inside the zkVM before being merkelized.

**Comment by aashutoshrathi** [comment]
ah! should we fix sizes or make them ints?

**Comment by 0xRampey** [comment]
We can fix size to 32 bytes perhaps. 
Arbitrary size is more practical use case for merkelization tho

**Comment by aashutoshrathi** [comment]
We do have this fixed now
