### ISSUE TITLE
ECDSA Verification

### ISSUE THREAD

**Issue by aashutoshrathi** [stackrlabs/succinct-residency-exps#48]
## Description

Take `n` as an argument, default test cases being `1`, `100`, `10,000`, `100,000`.
This means that we validate the signature `n` times.

Implement this in Rust & have a wasm-compiled version using `wasm-build` too.
Benchmark this on all zkVMs for native and Wasm.

Can leverage: https://crates.io/crates/ecdsa_verify

**Comment by eshaan7** [comment]
### Checklist

 - [x] native
 - [x] native_jolt
 - [x] native_risc_zero
 - [x] native_sp1
 - [x] wasm
 - [x] wasm_jolt
 - [x] wasm_risc_zero
 - [x] wasm_sp1
 - [ ] delphinus
 - [ ] native_nexus
 - [ ] wasm_nexus 
 - [ ] valida_program
