### ISSUE TITLE
Keccak

### ISSUE THREAD

**Issue by aashutoshrathi** [stackrlabs/succinct-residency-exps#51]
## Description

Take `n` as an argument, default test cases being `1`, `100`, `10,000`, and `100,000`.
Take a fixed data string and perform keccack on it `n` times.

Implement this in Rust & have a wasm-compiled version using `wasm-build` too.
Benchmark this on all zkVMs for native and Wasm.

**Comment by eshaan7** [comment]
### Checklist:

 - [x] native
 - [x] native_jolt
 - [x] native_risc_zero
 - [x] native_sp1
 - [x] wasm
 - [x] wasm_jolt
 - [x] wasm_risc_zero
 - [x] wasm_sp1
 - [ ] delphinus - wasm only
 - [ ] native_nexus
 - [ ] wasm_nexus 
 - [ ] valida_program
