### ISSUE TITLE
Poseidon Hash

### ISSUE THREAD

**Issue by aashutoshrathi** [stackrlabs/succinct-residency-exps#52]
## Description

Take `n` as an argument, default test cases being `1`, `100`, `10,000`, and `100,000`.
Take a random data string and hash it `n` times with Poseidon

Implement this in Rust & have a wasm-compiled version using `wasm-build` too.
Benchmark this on all zkVMs for native and Wasm.

Can leverage: https://crates.io/crates/poseidon-rs

**Comment by aashutoshrathi** [comment]
Ref this too: https://github.com/DelphinusLab/zkWasm-rust/blob/main/src/poseidon.rs

**Comment by eshaan7** [comment]
### Checklist

 - [x] native
 - [x] native_jolt
 - [x] native_risc_zero
 - [x] native_sp1
 - [x] wasm
 - [x] wasm_jolt
 - [x] wasm_risc_zero
 - [x] wasm_sp1
 - [ ] delphinus
 - [ ] native_nexus (code added but not working)
 - [ ] wasm_nexus 
 - [ ] valida_program
