### ISSUE TITLE
Merkle Generation

### ISSUE THREAD

**Issue by aashutoshrathi** [stackrlabs/succinct-residency-exps#53]
## Description

Take `n` as an argument representing leaves, default test cases being
- [x] 2
- [x] 2^10
- [x] 2^15
- [x] 2^20

Implement this in Rust & have a wasm-compiled version using `wasm-build` too.
Benchmark this on all zkVMs for native and Wasm.
Note: We already do have a Merklize for all the supported platforms, but for most we get OOM locally post 64 leaves.

**Comment by eshaan7** [comment]
### Checklist:

 - [x] native
 - [x] native_jolt
 - [x] native_risc_zero
 - [x] native_sp1
 - [x] wasm
 - [x] wasm_jolt
 - [x] wasm_risc_zero
 - [x] wasm_sp1
 - [x] delphinus
 - [ ] native_nexus
 - [ ] wasm_nexus 
 - [ ] valida_program
