### ISSUE TITLE
Merkle Inclusion Proof Generation

### ISSUE THREAD

**Issue by aashutoshrathi** [stackrlabs/succinct-residency-exps#54]
## Description

Take `n` as an argument, default test cases being `2^1`, `2^10`, `2^20`, and `2^30`.

We generate merkle inclusion proof of a node in this three of size `n`.

Implement this in Rust & have a wasm-compiled version using `wasm-build` too.
Benchmark this on all zkVMs for native and Wasm.

**Comment by eshaan7** [comment]
### Checklist:

 - [x] native
 - [x] native_jolt
 - [x] native_risc_zero
 - [x] native_sp1
 - [x] wasm
 - [x] wasm_jolt
 - [x] wasm_risc_zero
 - [x] wasm_sp1
 - [ ] delphinus - wasm only
 - [ ] native_nexus
 - [ ] wasm_nexus 
 - [ ] valida_program
